-- MySQL Script generated by MySQL Workbench
-- Fri Jul 31 08:59:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products` (
    `products_id` INT NOT NULL,
    `products_name` VARCHAR(45) NULL,
    PRIMARY KEY (`products_id`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `shop`.`sallers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`sallers` (
  `sallers_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`sallers_id`, `products_id`),
  INDEX `fk_sallers_products_idx` (`products_id` ASC),
  CONSTRAINT `fk_sallers_products`
    FOREIGN KEY (`products_id`)
    REFERENCES `shop`.`products` (`products_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`categories` (
  `categories_id` INT NOT NULL,
  `categories_name` VARCHAR(45) NULL,
  PRIMARY KEY (`categories_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`products_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products_has_categories` (
  `products_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `categories_id`),
  INDEX `fk_products_has_categories_categories1_idx` (`categories_id` ASC),
  INDEX `fk_products_has_categories_products1_idx` (`products_id` ASC),
  CONSTRAINT `fk_products_has_categories_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `shop`.`products` (`products_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `shop`.`categories` (`categories_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
